networks:
  proxy:
    external: true

services:
  app:
    container_name: php.${APP_NAME}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-user}
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - proxy

  nginx:
    image: nginx:stable-alpine
    container_name: nginx.${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - proxy
    ports:
      - "80:80"

  node:
    image: node:24
    container_name: node.${APP_NAME}
    environment:
      - VITE_HMR_HOST=${VITE_HMR_HOST}
      - VITE_HMR_PORT=${VITE_HMR_PORT}
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: /var/www/docker/scripts/node.sh
    depends_on:
      - app
    networks:
      - proxy

  postgres:
    container_name: postgres.${APP_NAME}
    image: postgres:17
    shm_size: 128mb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - proxy

volumes:
  postgres:

